//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioBook.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorBooks
    {
        public int IdAuthorBook { get; set; }
        public int IdAuthorAB { get; set; }
        public int IdBookAB { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
