//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioBook.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.AuthorBooks = new HashSet<AuthorBooks>();
            this.ReaderBooks = new HashSet<ReaderBooks>();
            this.Author2 = new HashSet<Author>();
        }
    
        public int IdBook { get; set; }
        public string NameBook { get; set; }
        public string TitleBook { get; set; }
        public string WayBook { get; set; }
        public int Genre { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> Reader { get; set; }
    
        public virtual Author Author1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorBooks> AuthorBooks { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Reader Reader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBooks> ReaderBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Author2 { get; set; }
    }
}
